"""Type stubs for can_motor_control."""

from __future__ import annotations

from collections.abc import Iterator
from typing import Any, ClassVar

import numpy as np

class DmError(Exception): ...
class TransportError(DmError): ...
class CodecError(DmError): ...
class ConfigError(DmError): ...
class LifecycleError(DmError): ...

class CanFrame:
    id: int
    flags: int
    len: int
    @classmethod
    def classical(cls, id: int, payload: bytes) -> "CanFrame": ...
    @classmethod
    def fd(cls, id: int, payload: bytes) -> "CanFrame": ...
    def payload(self) -> bytes: ...
    def is_fd(self) -> bool: ...
    def is_extended(self) -> bool: ...

class MockCanBus:
    def __init__(self, name: str) -> None: ...
    @staticmethod
    def new_fd(name: str) -> "MockCanBus": ...

class SocketCanBus:
    def __init__(self, interface: str, fd: bool = False) -> None: ...

class MotorSpec:
    def __init__(self, name: str, type: int, send_id: int, recv_id: int) -> None: ...

class Motor:
    name: str
    send_id: int
    recv_id: int
    position: float
    velocity: float
    torque: float
    temperature_mos: int
    temperature_rotor: int
    is_enabled: bool
    fault: int | None

class Arm:
    def __len__(self) -> int: ...
    def __getitem__(self, name: str) -> Motor: ...
    def positions(self) -> np.ndarray: ...
    def velocities(self) -> np.ndarray: ...
    def torques(self) -> np.ndarray: ...
    def mit_control(self, cmds: np.ndarray) -> None: ...
    def pos_vel_control(self, cmds: np.ndarray) -> None: ...
    def vel_control(self, cmds: np.ndarray) -> None: ...
    def pos_force_control(self, cmds: np.ndarray) -> None: ...
    def enable_all(self) -> None: ...
    def disable_all(self) -> None: ...
    def set_zero_all(self) -> None: ...
    def refresh(self) -> None: ...
    def set_mode(self, mode: str) -> None: ...

class Gripper:
    @property
    def motor(self) -> Motor: ...
    def enable(self) -> None: ...
    def disable(self) -> None: ...
    def mit_control(
        self, kp: float, kd: float, q: float, dq: float, tau: float
    ) -> None: ...
    def pos_vel_control(self, q: float, dq: float) -> None: ...
    def pos_force_control(self, q: float, dq: float, i_pu: float) -> None: ...
    def refresh(self) -> None: ...
    def set_mode(self, mode: str) -> None: ...

class MotorGroup:
    def __len__(self) -> int: ...

class RobotBuilder:
    def __init__(self) -> None: ...
    def add_bus(
        self, name: str, transport: Any, codec: Any
    ) -> "RobotBuilder": ...
    def add_arm(
        self, name: str, *, bus: str, motors: list[MotorSpec]
    ) -> "RobotBuilder": ...
    def add_gripper(
        self, name: str, *, bus: str, motor: MotorSpec
    ) -> "RobotBuilder": ...
    def add_generic(
        self, name: str, *, bus: str, motors: list[MotorSpec]
    ) -> "RobotBuilder": ...
    def build(self) -> "Robot": ...

class Robot:
    @classmethod
    def from_config(cls, path: str) -> "Robot": ...
    @classmethod
    def builder(cls) -> RobotBuilder: ...
    def connect(self) -> None: ...
    def enable(self) -> None: ...
    def disable(self) -> None: ...
    def tick(self, per_bus_deadline_us: int) -> None: ...
    def refresh(self) -> None: ...
    def set_mode(self, mode: str) -> None: ...
    def __enter__(self) -> "Robot": ...
    def __exit__(self, *exc: Any) -> None: ...
    def __getitem__(self, name: str) -> Arm | Gripper | MotorGroup: ...
    def __contains__(self, name: str) -> bool: ...
    def group_names(self) -> list[str]: ...
    def bus_names(self) -> list[str]: ...
    def is_connected(self) -> bool: ...
